name: mkdocs
services:
  mkdoc:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ecespedes/mkdocs:1.0.0
    container_name: mkdocs
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    restart: always
