name: mkdocs
services:
  mkdoc:
    build:
      context: .
      dockerfile: Dockerfile
    #image: python:3.9
    container_name: mkdocs
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app

    command: bash
volumes:
  .:
    external:
      name: .
