name: mkdocs
services:
  mkdoc:
    image: ecespedes/mkdocs:${VER:-latest}
    container_name: mkdocs
    stdin_open: true
    tty: true
    ports:
      - "${PORTMK:-8000}:8000"
    volumes:
      - .:/usr/src/app/
    restart: always

  web:
    image: nginx:latest
    container_name: website
    volumes:
      - ./${VPRO:-project}/site:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "${PORTNAV:-8080}:80"
    restart: always
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    image: php:8.0-fpm
    expose:
      - "9000"
    restart: always
    volumes:
      - ./${VPRO:-project}/site:/var/www/html
